# Modeling a Single Qubit

In [40]:
# Imports
import numpy as np 
import random
from collections import Counter

In [34]:
def normalize(x):
    return x / np.linalg.norm(x)

# Complex Number (a + bi)
j = np.sqrt(-1)

# Standard Basis Vectors
# e1 = |0>
# e2 = |1>
e1 = np.array([1,0]).T
e2 = np.array([0,1]).T

# Pauli Matrices
sig1 = np.array(([0,1], [1,0]))
sig2 = np.array(([0, -1j], [1j, 0]))
sig3 = np.array(([1,0], [0,-1]))

# Define adjoint or Hermitian conjugate 
def adjoint(x):
    return (np.conjugate(x)).T

# Check if Hermitian
def check_hermitian(x):
    """Checks if x is Hermitian

    Args:
        x (np.array): n x n matrix

    Returns:
        bool: True if Hermitian
    """
    res = adjoint(x) == x
    if np.all(res) == True:
        return True
    else:
        return False
    
def random_hermitian(n):
    """
    Randomly create n x n matrix and check if its hermitian returning the first one that is found.
    There is an instant implementation this one will only work for n < 5.

    Args:
        n (int): This will denote the size of the Hermitian
    
    Returns:
        np.array: Hermitian Matrix
    """
    rand = np.random.randint(0,n, size=(n,n))
    while check_hermitian(rand) != True:
        rand = np.random.randint(0,n, size=(n,n))
    return rand

def generate_evals_evectors(x):
    """ Generate the e-value and e-vectors of a matrix
    Args:
        x (Matrix): Any Matrix but for our purposes it will be Hermitian

    Returns:
        returns np.array objects, evals is a vector of the vals, evectors is a matrix of the vectors
    """
    return np.linalg.eigh(x)

def sample(H,psi):
    """
    What would we get if we measured the observable H in the quantum state psi?
    
    Args:
        H (Hermitian Matrix): Hermitian Matrix or Observable
        psi (Observable): Quantum State, in our case e1 or e2

    Returns:
        int : -1 or 1, simulating a quantum bit
    """
    e_vals,e_vectors = generate_evals_evectors(H)
    amplitude = np.abs(e_vectors.conj().T @ psi)**2
    return np.random.choice(e_vals, p = amplitude)


C:\Users\zuria\AppData\Local\Temp\ipykernel_2796\1425319827.py:5: RuntimeWarning: invalid value encountered in sqrt
  j = np.sqrt(-1)


In [30]:
hermitian_matrix = random_hermitian(4)

if check_hermitian(hermitian_matrix):
    print("This is Hermitian")
    print(hermitian_matrix)
else:
    print("This is not Hermiatian")
    print(hermitian_matrix)
    
e_vals,e_vector = generate_evals_evectors(hermitian_matrix)
print("E-Values")
print(e_vals)
print("E-Vectors")
print(e_vector)

This is Hermitian
[[1 1 1 1]
 [1 2 2 0]
 [1 2 0 1]
 [1 0 1 1]]
E-Values
[-1.5294459  -0.10780878  1.44752334  4.18973134]
E-Vectors
[[-0.01696177  0.81342282 -0.35448757 -0.46086243]
 [-0.46337926 -0.14181954  0.56496477 -0.6678186 ]
 [ 0.82621689 -0.25724717  0.02117886 -0.50074045]
 [-0.31993375 -0.50205023 -0.74478509 -0.3014683 ]]


## Simulating a Quantum Bits

In [35]:
res = []

for i in range(1000):
    paulis = [sig1,sig2,sig3]
    H = random.choice(paulis)
    if i % 2 == 0:
        psi = e1
    else:
        psi = e2
    res.append(sample(H,psi))
print(res)

[np.float64(1.0), np.float64(-1.0), np.float64(1.0), np.float64(-1.0), np.float64(1.0), np.float64(-1.0), np.float64(1.0), np.float64(-1.0), np.float64(1.0), np.float64(1.0), np.float64(-1.0), np.float64(1.0), np.float64(-1.0), np.float64(-1.0), np.float64(1.0), np.float64(-1.0), np.float64(1.0), np.float64(1.0), np.float64(1.0), np.float64(-1.0), np.float64(1.0), np.float64(-1.0), np.float64(-1.0), np.float64(-1.0), np.float64(1.0), np.float64(-1.0), np.float64(1.0), np.float64(1.0), np.float64(1.0), np.float64(1.0), np.float64(1.0), np.float64(1.0), np.float64(1.0), np.float64(-1.0), np.float64(1.0), np.float64(1.0), np.float64(-1.0), np.float64(-1.0), np.float64(1.0), np.float64(-1.0), np.float64(1.0), np.float64(-1.0), np.float64(1.0), np.float64(-1.0), np.float64(1.0), np.float64(1.0), np.float64(-1.0), np.float64(-1.0), np.float64(1.0), np.float64(-1.0), np.float64(1.0), np.float64(-1.0), np.float64(1.0), np.float64(-1.0), np.float64(1.0), np.float64(-1.0), np.float64(1.0), np.fl

In [ ]:
dictionary = Counter(res)
for key,val in dictionary.items():
    print(key , "Count:" , val)

1.0 Count: 507
-1.0 Count: 493
